In [1]:
%matplotlib inline
import matplotlib.pyplot as plt 
import numpy as np 
import seaborn as sns 

In [2]:
vector = np.array([1,2,3,4,5])

matriz = np.diag(vector)

matriz

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [3]:
matriz[0:4,0:3]

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3],
       [0, 0, 0]])

In [4]:
matriz[0:3,0:4]

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

In [6]:
a = np.diag([2,3,4,5])
a

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [7]:
v1 = np.array([1,1,1,1])
v1

array([1, 1, 1, 1])

In [8]:
a.dot(v1.T)

array([2, 3, 4, 5])

In [9]:
a_inv = np.diag([1/2,1/3,1/5,1/5])
a_inv

array([[0.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.        , 0.        ],
       [0.        , 0.        , 0.2       , 0.        ],
       [0.        , 0.        , 0.        , 0.2       ]])

In [10]:
identidad = a.dot(a_inv)
identidad

array([[1. , 0. , 0. , 0. ],
       [0. , 1. , 0. , 0. ],
       [0. , 0. , 0.8, 0. ],
       [0. , 0. , 0. , 1. ]])

In [12]:
a_inv_cal = np.linalg.inv(a)
a_inv_cal

array([[0.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.        , 0.        ],
       [0.        , 0.        , 0.25      , 0.        ],
       [0.        , 0.        , 0.        , 0.2       ]])

In [14]:
a.T

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [15]:
a

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [16]:
simetrica = np.array([[1,2,3],
                        [2,-1,7],
                        [3,7,11]])

simetrica

array([[ 1,  2,  3],
       [ 2, -1,  7],
       [ 3,  7, 11]])

In [17]:
simetrica.T

array([[ 1,  2,  3],
       [ 2, -1,  7],
       [ 3,  7, 11]])