In [1]:
import numpy as np 

In [4]:
escalar = 5,679
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])

tensor = np.array([
[[1,2,3,30],[4,5,6,31],[6,7,8,32]],
[[11,12,13,33],[14,15,16,34],[17,18,19,35]],
[[21,22,23,36],[24,25,26,37],[27,28,29,38]]
])

In [5]:
matriz_t = matriz.T
print(matriz_t)

[[1 3 5]
 [2 4 6]]


In [6]:
matriz

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
tensor

array([[[ 1,  2,  3, 30],
        [ 4,  5,  6, 31],
        [ 6,  7,  8, 32]],

       [[11, 12, 13, 33],
        [14, 15, 16, 34],
        [17, 18, 19, 35]],

       [[21, 22, 23, 36],
        [24, 25, 26, 37],
        [27, 28, 29, 38]]])

In [9]:
tensor_t = tensor.T
tensor_t

array([[[ 1, 11, 21],
        [ 4, 14, 24],
        [ 6, 17, 27]],

       [[ 2, 12, 22],
        [ 5, 15, 25],
        [ 7, 18, 28]],

       [[ 3, 13, 23],
        [ 6, 16, 26],
        [ 8, 19, 29]],

       [[30, 33, 36],
        [31, 34, 37],
        [32, 35, 38]]])

In [10]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[6,5],[4,3],[2,1]])
c = a+b
print(a)
print(b)
print(c)

[[1 2]
 [3 4]
 [5 6]]
[[6 5]
 [4 3]
 [2 1]]
[[7 7]
 [7 7]
 [7 7]]


In [13]:
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])
matriz_t = matriz.T

In [15]:
d = matriz_t+vector
d

array([[ 4,  7, 10],
       [ 5,  8, 11]])