In [1]:
%matplotlib inline
import matplotlib.pyplot as plt 
import numpy as np 
import seaborn as sns 

In [2]:
matriz = np.array([[1,0,0],
                    [0,1,0],
                    [0,0,1],
])
matriz

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
matriz[:,0].dot(matriz[:,1])

0

In [5]:
matriz[:,0].dot(matriz[:,2])

0

In [6]:
matriz[:,1].dot(matriz[:,2])

0

In [9]:
np.linalg.norm(matriz[:,0])


1.0

In [10]:
np.linalg.norm(matriz[:,1])


1.0

In [11]:
np.linalg.norm(matriz[:,2])

1.0

In [13]:
matriz[0,:].dot(matriz[1,:])

0

In [14]:
matriz[0,:].dot(matriz[2,:])

0

In [16]:
matriz[1,:].dot(matriz[2,:])

0

In [19]:
a = np.array([[np.cos(100), -np.sin(100)],
                [np.sin(100), np.cos(100)]])

print(a)

[[ 0.86231887  0.50636564]
 [-0.50636564  0.86231887]]


In [20]:
print(np.linalg.norm(a[0,:]))
print(np.linalg.norm(a[1,:]))
print(np.linalg.norm(a[:,0]))
print(np.linalg.norm(a[:,1]))

0.9999999999999999
0.9999999999999999
0.9999999999999999
0.9999999999999999


In [23]:
print(a[0,:].dot(a[1,:]))
print(a[:,0].dot(a[:,1]))

0.0
0.0


In [24]:
a_t = a.T 

In [25]:
print(a_t.dot(a))
print(a.dot(a_t))

[[ 1.00000000e+00 -7.93771519e-18]
 [-7.93771519e-18  1.00000000e+00]]
[[1.00000000e+00 7.93771519e-18]
 [7.93771519e-18 1.00000000e+00]]


In [26]:
a_inv = np.linalg.inv(a)
a_inv

array([[ 0.86231887, -0.50636564],
       [ 0.50636564,  0.86231887]])

In [27]:
a_t

array([[ 0.86231887, -0.50636564],
       [ 0.50636564,  0.86231887]])

In [28]:
print(1/a_t.dot(a))

[[ 1.00000000e+00 -1.25980837e+17]
 [-1.25980837e+17  1.00000000e+00]]
