In [1]:
import numpy as np

In [4]:
escalar = 5,679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [5]:
a = matriz * vector

In [6]:
b = matriz.dot(vector)

In [7]:
print(a)


[[ 2  6]
 [ 6 12]
 [10 18]]


In [8]:
print(b)

[ 8 18 28]


In [9]:
c = np.dot(matriz, vector)
print(c)

[ 8 18 28]


In [13]:
print(a.shape)

(4, 3)


In [14]:
print(b.shape)

(3, 2)


In [17]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b = np.array([[2,3],[5,7],[11,13]])
c = a.dot(b)
print(c)

[[ 45  56]
 [ 99 125]
 [153 194]
 [207 263]]
