In [1]:
import numpy as np

In [4]:
escalar = 5,679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])
a = np.array([[2,3],[5,7],[11,13]])
b = np.array([[1,3],[2,1]])
c = np.array([[3,1],[4,2]])

In [5]:
#asociativa
abc = a.dot(b.dot(c))
print(abc)

[[ 60  26]
 [145  63]
 [295 129]]


In [7]:
abc_2 = a.dot(b).dot(c)
print(abc_2)

[[ 60  26]
 [145  63]
 [295 129]]


In [9]:
#Distributiva
d = a.dot(b+c)
e = (a.dot(b))+(a.dot(c))

In [10]:
print(d)
print(e)

[[ 26  17]
 [ 62  41]
 [122  83]]
[[ 26  17]
 [ 62  41]
 [122  83]]


In [11]:
#conmutativa
f = b.dot(c)

In [12]:
g = c.dot(b)

In [13]:
print(f==g)

[[False False]
 [False False]]


In [14]:
print(f)
print(g)

[[15  7]
 [10  4]]
[[ 5 10]
 [ 8 14]]
