In [1]:
import numpy as np

In [2]:
a = np.array([[2,3],[5,7],[11,13]])
b = np.array([[1,3],[2,1]])

In [3]:
print(a)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [4]:
print(b)

[[1 3]
 [2 1]]


In [12]:
a.dot(b)

array([[ 8,  9],
       [19, 22],
       [37, 46]])

In [8]:
ab_t = a.dot(b).T
ab_t

array([[ 8, 19, 37],
       [ 9, 22, 46]])

In [9]:
b_ta_t = b.T.dot(a.T)
b_ta_t

array([[ 8, 19, 37],
       [ 9, 22, 46]])

In [7]:
print(ab_t == b_ta_t)

[[ True  True  True]
 [ True  True  True]]
