In [1]:
import numpy as np

In [2]:
identidad = np.eye(4)
identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
vector = np.array([[2],[3],[5],[7]])

In [4]:
identidad.dot(vector)

array([[2.],
       [3.],
       [5.],
       [7.]])

In [6]:
a = np.array([[1,0,1],[0,1,1],[-1,1,1]])
a

array([[ 1,  0,  1],
       [ 0,  1,  1],
       [-1,  1,  1]])

In [8]:
inversa_a = np.linalg.inv(a)
inversa_a

array([[ 0.,  1., -1.],
       [-1.,  2., -1.],
       [ 1., -1.,  1.]])

In [9]:
a.dot(inversa_a)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
singular = np.array([[1,1],[1,1]])
singular

array([[1, 1],
       [1, 1]])

In [12]:
#da error porque las matrices singular no tienen esta propiedad
#np.linalg.inv(singular)