In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress=True)

In [3]:
a = np.array([[3,1],[2,1]])
a

array([[3, 1],
       [2, 1]])

In [5]:
b = np.array([[1],[1]])
b

array([[1],
       [1]])

In [7]:
inversa_a = np.linalg.inv(a)
inversa_a

array([[ 1., -1.],
       [-2.,  3.]])

In [9]:
x = inversa_a.dot(b)
x

array([[0.],
       [1.]])

In [10]:
a.dot(x)

array([[1.],
       [1.]])